import { IEvent } from '../interfaces/event';

export const EVENTS: IEvent[] = [
  {
    ID: 1,
    Email: 'huegogh@gmail.com',
    Petname: 'Tauni',
    Datetime: 'May 10, 2021 09:00:00',
    Occurrence: 'Once',
    EventType: 'Grooming',
  },
  {
    ID: 2,
    Email: 'huegogh@gmail.com',
    Petname: 'Yoda',
    Datetime: 'May 10, 2021 09:00:00',
    Occurrence: 'Daily',
    EventType: 'Feeding',
  },
  {
    ID: 3,
    Email: 'huegogh@gmail.com',
    Petname: 'Triton',
    Datetime: 'May 10, 2021 09:00:00',
    Occurrence: 'Daily',
    EventType: 'Grooming',
  },
  {
    ID: 4,
    Email: 'huegogh@gmail.com',
    Petname: 'Nala',
    Datetime: 'May 10, 2021 09:00:00',
    Occurrence: 'Daily',
    EventType: 'Grooming',
  },
  {
    ID: 5,
    Email: 'huegogh@gmail.com',
    Petname: 'Lyra',
    Datetime: 'May 10, 2021 09:00:00',
    Occurrence: 'Daily',
    EventType: 'Grooming',
  },
  {
    ID: 6,
    Email: 'huegogh@gmail.com',
    Petname: 'Webster',
    Datetime: 'May 10, 2021 09:00:00',
    Occurrence: 'Daily',
    EventType: 'Grooming',
  },
  {
    ID: 7,
    Email: 'huegogh@gmail.com',
    Petname: 'Albert',
    Datetime: 'May 10, 2021 09:00:00',
    Occurrence: 'Daily',
    EventType: 'Grooming',
  },
  {
    ID: 8,
    Email: 'huegogh@gmail.com',
    Petname: 'Ochaco-chan',
    Datetime: 'May 10, 2021 09:00:00',
    Occurrence: 'Daily',
    EventType: 'Grooming',
  },
];
